### ISSUE TITLE
SSL errors on https://www.void.gr/kargig/void-gr-filters.txt

### ISSUE THREAD

**Issue by ryanbr** [kargig/greek-adblockplus-filter#101]
Hey, 

Just notifying the list has SSL Cert errors on https://www.void.gr/kargig/void-gr-filters.txt

`NET::ERR_CERT_DATE_INVALID`

**Comment by Vangelis66** [comment]
Yes, the certificate on `www.void.gr` expired on **Mar 17th 06:01 UTC** 👎 , thus the secure connection can no longer be established (by default) ...

The **uB0-legacy** (v1.16.4.**28**) embedded filter list (**GRC: Greek AdBlock Filter**) uses by default the `www.void.gr` hostname and can't currently be updated; once disabled, it can no longer be populated again by re-enabling it... 😞 

As an interim workaround, until such time as the cert is renewed, I have disabled the embedded list and added **Greek AdBlock Filter** as a **custom** filter list via: 

https://github.com/kargig/greek-adblockplus-filter/raw/master/void-gr-filters.txt

**Comment by kargig** [comment]
Thanks for catching this!

This has been fixed,  nginx had not been reloaded after cert renewal, can you please revert brave/adblock-resources#22 now ?

**Comment by ryanbr** [comment]
We have a number of lists using Github, and it's probably the most reliable for hosting a list. Is it fine to keep the list source on Github?

**Comment by kargig** [comment]
The list contains: `! Redirect: https://www.void.gr/kargig/void-gr-filters.txt`, is this respected by brave, so first rule fetch from github and all subsequent updates from void.gr, or will all brave filter updates be coming from github with your change ?

In any case, I can't force you to make any change, the final call is yours :)

**Comment by ryanbr** [comment]
Unfortunately we don't support the ! redirect option so it'll just grab the github list regardless. If your preference isn't github, we'll respect your wishes.

**Comment by kargig** [comment]
it's OK then, leave it as it is

thanks again for catching the problem and raising an issue here
