### ISSUE TITLE
[NSFW] [ADS] sexgr.net

### ISSUE THREAD

**Issue by felix-22** [kargig/greek-adblockplus-filter#107]
Two issues:
- ADS and ADS placeholders (on the left side) (Firefox)
- Breakage (reported already to https://github.com/easylist/easylist/issues/9190)

<details not-open>
<summary>ADS screenshoot Firefox</summary>

![2222](https://user-images.githubusercontent.com/75935068/134310925-fcb1f699-9f63-4985-b726-06b03587b1b2.png)
</details>

<details not-open>
<summary>Opera screenshoot, can't load page</summary>

![oo](https://user-images.githubusercontent.com/75935068/134311498-4d8c01fc-17a6-4b08-b62d-25c450da2f9c.png)

</details>

**Comment by kargig** [comment]
feel free to submit a PR. If you don't know how, maybe @aldi can help
