### ISSUE TITLE
ygeiaonline.gr booking ad

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#111]
https://www.ygeiaonline.gr/listing/%CE%B1%CE%B8%CE%AE%CE%BD%CE%B1/%CE%B3%CE%B9%CE%B1%CF%84%CF%81%CE%BF%CE%AF/%CF%83%CE%B2%CE%BF%CE%BB%CE%BF%CF%80%CE%BF%CF%85%CE%BB%CE%BF%CF%85-%CE%B1%CE%B9%CE%BA%CE%B1%CF%84%CE%B5%CF%81%CE%B9%CE%BD%CE%B7/

Screenshot:
![Screenshot 2022-09-06 at 07-45-19 Σβολοπουλου Αικατερινη](https://user-images.githubusercontent.com/101707608/188549003-d3836fcb-5632-4af3-9866-6134a6da789d.png)

Suggested filter:
ygeiaonline.gr##.booking-sticky-footer

**Comment by kargig** [comment]
Can you explain why you consider this an advertisement please ?

**Comment by DimitrisKalaboukas** [comment]
It’s a booking ad footer in a health site.

**Comment by kargig** [comment]
Which filter lists are you using ? These ads are blocked for me by uBlock's default list

**Comment by DimitrisKalaboukas** [comment]
All filters offered by uBlock Origin. But the ad footer isn’t blocked, unless I add the above mentioned filter.

**Comment by DimitrisKalaboukas** [comment]
@kargig Paradoxically, the ad footer appears only in high zoom percentage, as shown in the provided screenshot.

**Comment by DimitrisKalaboukas** [comment]
@zloyden ?

**Comment by zloyden** [comment]
@kargig @DimitrisKalaboukas could you explain the purpose of this?
As far as I understand, the site is informational and its theme is about health, but it is not related to the provision of medical services. At first glance, this element does not appear to be an advertisement - I do not see any redirects to external resources in the code, but it is strange that the button itself is non-functional. Nothing happens when clicked.

**Comment by DimitrisKalaboukas** [comment]
@zloyden Anyway, this footer is at least an annoyance, since it isn’t even functional.

**Comment by zloyden** [comment]
Seems to be so, I only see it on mobile, so I've added it to our Annoyances filter.

**Comment by DimitrisKalaboukas** [comment]
@zloyden Since it also appears on desktop in higher zoom rate, I think that it shouldn’t be platform-dependent.
