### ISSUE TITLE
Skroutz's new spam

### ISSUE THREAD

**Issue by epigramx** [kargig/greek-adblockplus-filter#112]
Skroutz added some very intrusive spamming lately (easy to miss the fine print since they have the exact same format with legit results), and I don't know how to filter it since the regular picking tool of ublock doesn't encompass it.

![image](https://user-images.githubusercontent.com/2960257/189544154-2db29e2b-fc85-44b5-a899-11d53c709499.png)

source: https://www.skroutz.gr/c/55/kartes-grafikwn-vga.html

**Comment by kargig** [comment]
See my reply in a PR proposing to block these: https://github.com/kargig/greek-adblockplus-filter/pull/110#issuecomment-1214435858

I don't think removing these internal promotions for the website belong in an adblock filter

**Comment by epigramx** [comment]
They are ads, because they wouldn't be ads only if you can't find those results again but they are duplicated right below them.
These appear to cover it
```
www.skroutz.gr##.labeled-item.with-skus-slider.card.cf
www.skroutz.gr##li.labeled-product.labeled-item.card.cf
```
