### ISSUE TITLE
papoutsanis.gr footer ad

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#113]
https://www.papoutsanis.gr/el/markes-katanalotikon-proionton/karavaki-brand/

Screenshot:
![Screenshot 2022-09-29 at 16-40-49 KARAVAKI Μάρκες Καταναλωτικών Προϊόντων Papoutsanis](https://user-images.githubusercontent.com/101707608/193049365-5ed7a323-d3e9-463a-9742-451fc339bd0b.png)

Suggested filter:
papoutsanis.gr##div.promo-popup-container

**Comment by elkargig** [comment]
that's not an advertisement. it may be annoying, but it's an internal informational banner from the website. You can use adblock or any other similar tool to remove it, but it doesn't belong to an adblock list
