### ISSUE TITLE
new secretive-ish ads by skroutz.gr

### ISSUE THREAD

**Issue by epigramx** [kargig/greek-adblockplus-filter#117]
They appear to have a whole section now/again above the main section that features sponsored products but they are also repeated below so they are obviously ads and unnecessary (since they are repeated).

e.g. 
![image](https://user-images.githubusercontent.com/2960257/210341937-453f8f38-d610-4ee1-8adf-362a122cc96e.png)
https://www.skroutz.gr/s/4026375/Fissler-Vitaquick-%CE%A7%CF%8D%CF%84%CF%81%CE%B1-%CE%A4%CE%B1%CF%87%CF%8D%CF%84%CE%B7%CF%84%CE%B1%CF%82-8lt.html

it appears to be gone with 
`##.non-featured-sku.featured-product-card`

**Comment by kargig** [comment]
This is now: `skroutz.gr##.selected-product-cards`
