### ISSUE TITLE
Important features of the website meteo.gr are being blocked by this filter

### ISSUE THREAD

**Issue by GeorgeGR21** [kargig/greek-adblockplus-filter#126]
**This website is one of Greece's largest weather services and some important features do not work when this filter is enabled.**

https://meteo.gr/dustMaps.cfm: There should be a dust map below the timeline buttons.

https://meteo.gr/yetosmaps.cfm: It's the same story as the one above, but for rain and pressure.

https://meteo.gr/atf_map.cfm: A map of Attica should appear here.

https://meteo.gr/ForecastsHours.cfm: A map of Greece with forecasts should appear here.

https://meteo.gr/roads/: Here should be a map that shows road conditions due to weather.

**Comment by kargig** [comment]
thanks for reporting this, can you update the filters and check if you still see the problem ?

**Comment by GeorgeGR21** [comment]
All of them work now, except https://meteo.gr/roads/ which is still not working.
