### ISSUE TITLE
Lidl Ergasia website completely blocked when filter is enabled

### ISSUE THREAD

**Issue by GeorgeGR21** [kargig/greek-adblockplus-filter#136]
The whole website is being blocked when the filter is enabled in uBlock Origin. This results in only the header and footer being visible and you need to completely turn off the adblocker to make the website work.

Link: `https://team.lidl.gr/anazitisi-ergasias-lidl-ellas`

Screenshot with **uBlock Origin turned ON**:
![Screenshot from 2023-09-18 20-49-13](https://github.com/kargig/greek-adblockplus-filter/assets/123986260/a935d22e-a0ec-4679-b6fb-e3e94f59ab9c)
Screenshot with **uBlock Origin turned OFF**:
![Screenshot from 2023-09-18 20-49-23](https://github.com/kargig/greek-adblockplus-filter/assets/123986260/56bcc8dc-d066-4972-be32-8d4ea9212a8a)

**Comment by kargig** [comment]
the greek filters don't block anything included from `https://team.lidl.gr/anazitisi-ergasias-lidl-ellas`. Any blocks from other lists should be visible if you open the ublock logger:
![image](https://github.com/kargig/greek-adblockplus-filter/assets/613783/06845b4f-15b4-42cd-ada5-a2be667d0ab1)

you can then reload the page and check the logger to see which filter rule is blocking the elements you need. That will also show you which list contains that rule and then you can report the problem to that list and/or ask for an exception

**Comment by GeorgeGR21** [comment]
You're right, my bad.
