### ISSUE TITLE
galinos.gr ad leftover space and ad blocker detection

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#140]
https://www.galinos.gr/web/drugs/main/substances/amisulpride/pharmacology

![Screenshot 2023-11-05 at 10-02-11 Γαληνός - Δραστική ουσία - Αμισουλπρίδη - Φαρμακολογία](https://github.com/kargig/greek-adblockplus-filter/assets/101707608/13cb6cee-1b03-42ed-b854-3d78634f2d40)

Suggested filters:
galinos.gr##.header-billboard
galinos.gr##div.white.stripe.row:has-text(Ad Blocker)

**Comment by kargig** [comment]
fixed by https://github.com/kargig/greek-adblockplus-filter/commit/ca235c3361f402c5da908ae3460e27cc5b85d8cd
I did not remove the remove adblocker banner, as that's not an ad by itself

**Comment by DimitrisKalaboukas** [comment]
@kargig The list isn't syncing again:

https://www.void.gr/kargig/void-gr-filters.txt

**Comment by kargig** [comment]
> @kargig The list isn't syncing again:
> 
> https://www.void.gr/kargig/void-gr-filters.txt

Thanks for the report, it's working now again
