### ISSUE TITLE
Ad holders in flash.gr

### ISSUE THREAD

**Issue by PhoenixFossGR** [kargig/greek-adblockplus-filter#143]
There are multiple ad holders all across the website flash.gr.

Here is an example URL: `https://www.flash.gr/se-rythmoys-christoygennon-i-athina-stithike-sto-syntagma-to-dentro-xekinise-o-stolismos-904343`

Screenshot:

![Screenshot from 2023-11-24 19-44-41](https://github.com/kargig/greek-adblockplus-filter/assets/123986260/3d5bda4f-ad61-4766-9bc2-47855ced46ed)

**Comment by kargig** [comment]
fixed via https://github.com/kargig/greek-adblockplus-filter/commit/4fc4888e2ed848cbf75ac53df4a4520cda88ce2a
