### ISSUE TITLE
grland.info: Multiple empty ad banners

### ISSUE THREAD

**Issue by PhoenixFossGR** [kargig/greek-adblockplus-filter#145]
There are multiple empty ad banners and boxes on the following link:

`https://www.grland.info/`

Screenshots:
![Screenshot from 2023-12-03 21-20-53](https://github.com/kargig/greek-adblockplus-filter/assets/123986260/ac0a9e8b-566b-402d-b013-83c625dd7b66)
![Screenshot from 2023-12-03 21-20-57](https://github.com/kargig/greek-adblockplus-filter/assets/123986260/3fc49dad-cf8b-4028-9736-2b00eb4d7dd1)
![Screenshot from 2023-12-03 21-21-08](https://github.com/kargig/greek-adblockplus-filter/assets/123986260/b70a7aea-9139-446a-a0e7-90f20e83a023)
![Screenshot from 2023-12-03 21-21-15](https://github.com/kargig/greek-adblockplus-filter/assets/123986260/b07a9e7a-7753-4fa5-a97c-0f15220b0a1c)

**Comment by kargig** [comment]
this site is just ad banners, I don't think it's worth trying to remove every single one of them, just avoid using it :)
