### ISSUE TITLE
newsbeast.gr: detection

### ISSUE THREAD

**Issue by patrickdrd** [kargig/greek-adblockplus-filter#147]
https://www.newsbeast.gr/lifestyle/arthro/10315101/den-thelo-gamo-tha-tsakothoume-epeidi-den-vazei-plyntirio-eipe-o-giannis-tsimitselis-gia-tin-katerina-geronikolou

adblock detect when pressing play on video:
![image](https://github.com/kargig/greek-adblockplus-filter/assets/24896778/2b078586-2e8f-4e47-a501-26f46523ca2f)

previously opened here:
https://github.com/uBlockOrigin/uAssets/issues/21361

**Comment by kargig** [comment]
I don't get this problem. Do you still see this? If yes, which filter lists are you using ?

**Comment by patrickdrd** [comment]
it's working now, should have been a temporary issue

**Comment by BillyCool** [comment]
Adblock appears to be detected again on my end. Same link and behavior as OP.

**Comment by kargig** [comment]
still not detected on my side, can you post some more info maybe from ublock logger that shows the problematic request ?

**Comment by BillyCool** [comment]
I did a bit more testing and it looks like when connecting to a VPN, the videos are playing normally. I tried connecting to a few different countries and they're all ok, the issue only comes up when not using a VPN, so not sure what's wrong there. I'm not 100% sure what requests to look for, but I'm not seeing anything related to adblock detection under network. Not as big of a deal since I have a workaround for now.

**Comment by kargig** [comment]
are there specific pages giving you this problem or is it all of them ?
can you try with some other browser ? e.g. chrome + ublock or brave + ublock ?
I can't reproduce with or without a VPN

**Comment by BillyCool** [comment]
It was all pages, but I managed to trace down the issue. It was indeed not an issue with the filter list but my DNS-level blocking. More specifically, it was the blocking of imasdk.googleapis.com of all things that caused the adblock detection to be triggered. Whitelisted the domain and everything is good now!

**Comment by kargig** [comment]
great news, thanks for reporting how you fixed it!
