### ISSUE TITLE
techgear.gr ad leftover space

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#152]
https://www.techgear.gr/ee-kai-apple-se-krisimes-syzitiseis-gia-to-sideloading-kai-ochi-mono-37013

![Screenshot 2024-01-18 at 16-18-00 ΕΕ και Apple σε κρίσιμες συζητήσεις για το sideloading και όχι μόνο](https://github.com/kargig/greek-adblockplus-filter/assets/101707608/a02e91b2-c042-433b-a68e-8e09bfb0b5ab)

Suggested filters:
techgear.gr##.ad__div
techgear.gr##.ad__mobile

**Comment by kargig** [comment]
should be fixed by https://github.com/kargig/greek-adblockplus-filter/commit/ddcec1eeccb84e22340631afb65c4ff0e8c86d03
Re-open if it doesn't work as expected
