### ISSUE TITLE
enikos.gr ad leftover spaces

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#153]
https://www.enikos.gr/economy/psifiakes-apates-etsi-tha-prostateftheite-apo-to-vishing-to-phishing-kai-to-smishing-10-erotiseis-kai-apantiseis/2095079/

Suggested filters:
enikos.gr###article-ad-container1
enikos.gr###article-ad-container3
enikos.gr###article-inread-ad-container

**Comment by kargig** [comment]
your filter suggestions were correct, next time try and create a PR :)
