### ISSUE TITLE
unboxholics.com ad leftover spaces

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#155]
https://unboxholics.com/news/tech/111797-ios-174-afti-i-allagi-tha-epireasei-olous-tous-christes-iphone-me-ti-nea-anavathmisi

Suggested filters:
unboxholics.com###inside-banner-1
unboxholics.com###inside-banner-2
unboxholics.com###inside-banner-3

**Comment by kargig** [comment]
should be fixed via https://github.com/kargig/greek-adblockplus-filter/commit/4909ef1eaf71e489e5f14892984f7e40a06acbfa

**Comment by DimitrisKalaboukas** [comment]
@kargig Please, add:

unboxholics.com##.banner-inline-read

to hide a small leftover space. Also, the list isn't syncing again.

**Comment by kargig** [comment]
The list updates every 5 minutes, last update at: `Feb  5 16:30 void-gr-filters.txt`
