### ISSUE TITLE
iefimerida.gr ad leftover spaces

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#156]
https://www.iefimerida.gr/ellada/mmm-amea-gia-prosbasi-se-stathmoys

Suggested filters:
iefimerida.gr###storyteller-box
iefimerida.gr###taboola-alternating-below-article-3

**Comment by kargig** [comment]
can you provide a screenshot? I don't see any leftover spaces with easylist + greek filters

**Comment by DimitrisKalaboukas** [comment]
@kargig Maybe they only appear at 150% zoom ratio:

![Screenshot 2024-02-05 at 11-38-00 ΜΜΜ Από 1ης Φεβρουαρίου τα ΑμεΑ θα μπορούν να ενημερωθούν για την πρόσβαση σε σταθμούς μέσω του σάιτ της ΣΤΑΣΥ - ief](https://github.com/kargig/greek-adblockplus-filter/assets/101707608/bff986bb-83e6-4c7c-a39f-12ca18676b4b)
