### ISSUE TITLE
queen.gr ad leftover spaces

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#158]
https://www.queen.gr/power-to-inspire/empowerment/story/284223/lilian-balatsoy-yparxei-entoni-emfyli-dysanalogia-se-posotiko-kai-poiotiko-epipedo-stin-epistimi

They appear if you zoom-in or from mobile device.

Suggested filter:
queen.gr##.inline-banner

**Comment by DimitrisKalaboukas** [comment]
@kargig This filter doesn't fix the issue on mobile devices or in high zoom rate. You should use:

queen.gr##.inline-banner

or

queen.gr##.mobile-banner

**Comment by DimitrisKalaboukas** [comment]
@Alex-302 ?

**Comment by Alex-302** [comment]
@DimitrisKalaboukas Fixed.
