### ISSUE TITLE
void.gr: IPv6 connectivity issues

### ISSUE THREAD

**Issue by Gittyperson** [kargig/greek-adblockplus-filter#164]
It appears that the website is having IPv6 issues and some browsers (e.g. Pale Moon, Brave) are having trouble downloading and updating the filterlist, depending on network configuration:

https://www.ssllabs.com/ssltest/analyze.html?d=www.void.gr

![IPv6](https://github.com/kargig/greek-adblockplus-filter/assets/7165208/15b32ebf-236b-4364-ae0b-778405d598df)

**Comment by kargig** [comment]
Thanks a lot for the report. Fixed after some troubleshooting with the upstream network:
![image](https://github.com/kargig/greek-adblockplus-filter/assets/613783/e1690f57-42e2-45b1-8dfa-0907e74baf63)
