### ISSUE TITLE
[Feature Request] Add Support of uBlock Origin's Procedural cosmetic filters

### ISSUE THREAD

**Issue by ghost** [kargig/greek-adblockplus-filter#169]
@kargig 
https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters

**Specifically:**
:has()
:has-text()
:upward()

**Comment by kargig** [comment]
Nothing prevents people from suggesting rules containing those procedural cosmetic filters as far as I know.
What exactly is the pending issue/action item here ?
