### ISSUE TITLE
newsbomb.gr ad banner spaces

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#170]
https://www.newsbomb.gr/kosmos/story/1553646/antistrofi-metrisi-gia-tis-evroekloges-2024-analytika-ola-ta-stoixeia-kai-oi-arithmoi

Suggested filters:
newsbomb.gr##.inline-banner
newsbomb.gr##.mobile-banner

**Comment by DimitrisKalaboukas** [comment]
@Alex-302 ?

**Comment by DimitrisKalaboukas** [comment]
@zloyden ?

**Comment by kargig** [comment]
can you post a screenshot with the ads / ad spaces you see and want removed ?

**Comment by DimitrisKalaboukas** [comment]
@kargig At the moment, it seems that the issue has been fixed by default ad blocking lists.
