### ISSUE TITLE
real.gr ad banners

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#174]
https://www.real.gr/kosmos/arthro/o_elon_mask_apokalyptei_gia_to_trans_paidi_tou_me_ksegelasan_me_ebalan_na_ypograpso_kati_eggrafa_gia_ton_gio_mou-1034933/

Suggested filter:
real.gr##.banner-wrapper

**Comment by kargig** [comment]
I don't see this banner, can you post a screenshot please ?

**Comment by DimitrisKalaboukas** [comment]
@kargig The blank spaces between topics:

![Screenshot 2024-07-27 at 12-04-59 Ο Έλον Μασκ αποκαλύπτει για το τρανς παιδί του Με ξεγέλασαν με έβαλαν να υπογράψω κάτι έγγραφα για τον γιο μου](https://github.com/user-attachments/assets/e647dbbd-20ef-44d6-94f8-02f60fd3a926)
