### ISSUE TITLE
tirnavospress.gr: ads

### ISSUE THREAD

**Issue by MEtICaRT** [kargig/greek-adblockplus-filter#177]
https://tirnavospress.gr

This website is full of images and GIFs with ads. It's even worse inside articles.

**Comment by kargig** [comment]
feel free to suggest filters

**Comment by MEtICaRT** [comment]
I don't know much about filters themselves and I'm really bad at these, but this is my try:

```
||tirnavospress.gr/wp-content/uploads/2024/01/BRALI-02-scaled-3.jpg
###sidebar
||tirnavospress.gr/wp-content/uploads/2024/01/en_tirnavo_logo_2024.gif
||tirnavospress.gr/wp-content/uploads/2024/01/ktima_vrisi_banner.gif
||tirnavospress.gr/wp-content/uploads/2023/09/check_up_labs-1.jpg
###under-post-content.section
##.content-inner > .footer-wide.section
```

I'm talking about ads like those:
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/0f985e9a-153a-4b8c-90cd-576a31d95d88">
