### ISSUE TITLE
spitogatos.gr ad spaces before footer

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [kargig/greek-adblockplus-filter#189]
https://www.spitogatos.gr/enoikiaseis-katoikies/peristeri

Suggested rule:
spitogatos.gr##.seo-links__adv1,.seo-links__adv2,.seo-links__adv3
(the first appears on desktop, all three on mobile)

You may need to be signed in to reproduce them.

**Comment by kargig** [comment]
Can you post some screenshots of the problematic elements ?

**Comment by DimitrisKalaboukas** [comment]
@kargig On desktop it's this space:

![Screenshot 2024-11-11 at 11-15-50 Ενοικιάσεις κατοικιών Περιστέρι (Αθήνα - Δυτικά Προάστια) Spitogatos](https://github.com/user-attachments/assets/8638942c-0070-4c0e-a5a7-d8910ef6309f)

On mobile it's triple on height.

**Comment by kargig** [comment]
this may be annoying, but there are no ads displayed there, right ? This is part of the functionality of the website (SEO enhancement)

**Comment by DimitrisKalaboukas** [comment]
@kargig OK, I'll just use the rule in my own custom filters.
