### ISSUE TITLE
sarajevotimes.com: detection (“AdBlock Detected”)

### ISSUE THREAD

**Issue by elsandosgrande** [kargig/greek-adblockplus-filter#198]
Enabling the Greek AdBlock Filter list in uBlock Origin leads to the detection of uBlock Origin by Sarajevo Times. See https://github.com/uBlockOrigin/uAssets/issues/26439 for further information.

**Comment by kargig** [comment]
The problem should be fixed by https://github.com/kargig/greek-adblockplus-filter/commit/fd157a6ff807b7d51abb573ec4db3df5c910dd65
Let me know if it's still an issue after updating the filters

**Comment by elsandosgrande** [comment]
Looks like everything's fine now. Thanks!!
