### ISSUE TITLE
The Void.gr version of your list is outdated

### ISSUE THREAD

**Issue by DandelionSprout** [kargig/greek-adblockplus-filter#33]
Greetings, Dandelion Sprout here, the maintainer of *Dandelion Sprout's Nordic Filters*.

While looking into uBlock Origin-included lists that hadn't been updated in a while, I discovered that [the Void.gr version](https://www.void.gr/kargig/void-gr-filters.txt) of your list has not received any of the GitHub-commited updates [from November or December](https://github.com/kargig/greek-adblockplus-filter/commits/master), and that it still shows the 1st of May as its version date.

Since it's the Void.gr version that is included in uBlock Origin and Nano Adblocker: Is it merely a synchronising error that you hope to fix, or should I send a message to the uBO team to ask them to change the subscription link to [the more recently updated GitHub version](https://raw.githubusercontent.com/kargig/greek-adblockplus-filter/master/void-gr-filters.txt)?

**Comment by kargig** [comment]
syncing issue fixed. Thanks for noticing.
