### ISSUE TITLE
filadelfia-xalkidona.gr

### ISSUE THREAD

**Issue by patrickdrd** [kargig/greek-adblockplus-filter#34]
full of ads site

add these too:
https://github.com/uBlockOrigin/uAssets/issues/4567

**Comment by patrickdrd** [comment]
more rules suggested:

`anekshghta.blogspot.com###cboxLoadedContent
anekshghta.blogspot.com###cboxContent
anekshghta.blogspot.com###cboxWrapper
anekshghta.blogspot.com###colorbox
anekshghta.blogspot.com###cboxOverlay

||anikolouli.gr/wp-content/uploads/bg_Main.jpg$image
anikolouli.gr##[id^="popmake-"]
||anikolouli.gr/wp-content/uploads/bg_Main.jpg$image
anikolouli.gr##[src*="/banners/"]
apergies.blogspot.com##[href="http://europaints.blogspot.com"]
||www.blogblog.com/1kt/transparent/black50.png$image

elculture.gr###snow

elapopsigalatsiou.blogspot.com##.newsticker

||www.imerodromos.gr/wp-content/uploads/2018/05/Tiniakosgr.gif$image
||www.imerodromos.gr/wp-content/uploads/2018/11/500X417_COLUMBIA.jpg$image
||www.imerodromos.gr/wp-content/uploads/2018/11/500X417_MARCOS.jpg$image
||www.imerodromos.gr/wp-content/uploads/2018/11/500X417_MARX.jpg$image
||www.imerodromos.gr/wp-content/uploads/2018/07/BoukoviBanner-500x417.jpg$image
||www.imerodromos.gr/wp-content/uploads/2018/12/MEGALH-ISTORIA-THS-ELLADAS-2.jpg$image
||www.imerodromos.gr/wp-content/uploads/2018/12/MEGALH-ISTORIA-THS-ELLADAS-1.jpg$image
||www.imerodromos.gr/wp-content/uploads/2017/06/collectives1-20.jpg$image
www.imerodromos.gr##.elementor-top-section.elementor-section.elementor-section-height-default.elementor-section-boxed.elementor-element-4162913.elementor-element.has_ae_slider > .elementor-column-gap-default.elementor-container > .elementor-row
||www.imerodromos.gr/wp-content/uploads/2018/07/kraounakis1.jpg$image
||www.imerodromos.gr/wp-content/uploads/2018/12/na_ntysoume_tous_gymnous_500x417pix-2-1.gif$image
www.imerodromos.gr##.elementor-inner-column.elementor-col-33.elementor-column.elementor-element-7e87.elementor-element.has_ae_slider > .elementor-element-populated.elementor-column-wrap
||www.imerodromos.gr/wp-content/uploads/2017/02/podium-2.gif$image
||www.imerodromos.gr/wp-content/uploads/2018/05/Screen-Shot-2018-05-07-at-20.41.56.png$image
||www.imerodromos.gr/wp-content/uploads/2018/04/BANER_ASFALISTIKO_300X249.jpg$image
www.imerodromos.gr##.elementor-top-column.elementor-col-50.elementor-column.elementor-element-fc62ef0.elementor-element.has_ae_slider > .elementor-element-populated.elementor-column-wrap > .elementor-widget-wrap

www.intos.gr###intro
www.intos.gr###HTML1

||static.larissanet.gr/wp-content/uploads/2018/10/201810092144051519.jpg$image
||static.larissanet.gr/wp-content/themes/larissanet/images/backgrounds/larissanet_red.jpg$image
www.larissanet.gr##.side_banner_left
||static.larissanet.gr/wp-content/uploads/2018/09/201809171844172677.gif$image
||static.larissanet.gr/wp-content/uploads/2019/01/201901020726459665.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/11/201811271248115852.gif$image
||static.larissanet.gr/wp-content/uploads/2018/03/201803191535332443.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/09/201809071403114459.gif$image
||static.larissanet.gr/wp-content/uploads/2018/03/201803231213525881.gif$image
||static.larissanet.gr/wp-content/uploads/2018/07/201807171426379875.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/09/201809211524131649.gif$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812311316359200.png$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812241138495306.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812120920298578.jpg$image
||static.larissanet.gr/wp-content/uploads/2019/01/201901041826244393.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812141126465540.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812201233117632.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/11/201811091757448560.gif$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812101753009866.jpg$image
||static.larissanet.gr/wp-content/uploads/2019/01/201901070911164806.png$image
||static.larissanet.gr/wp-content/uploads/2018/09/201809141439594711.gif$image
||static.larissanet.gr/wp-content/uploads/2018/11/201811150948467914.gif$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812011034236964.gif$image
||static.larissanet.gr/wp-content/uploads/2019/01/201901041153026102.gif$image
||static.larissanet.gr/wp-content/uploads/2018/12/201812101749324075.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/11/201811141752325364.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/07/201807102057014619.gif$image
||static.larissanet.gr/wp-content/uploads/2018/11/201811300843033218.jpg$image
||static.larissanet.gr/wp-content/uploads/2017/02/201702072033081374.gif$image
||static.larissanet.gr/wp-content/uploads/2018/08/201808021549217920.gif$image
||static.larissanet.gr/wp-content/uploads/2017/10/201710051837474650.png$image
||static.larissanet.gr/wp-content/uploads/2017/05/201705260852253988.gif$image
||static.larissanet.gr/wp-content/uploads/2018/11/201811211746314674.jpg$image
||static.larissanet.gr/wp-content/uploads/2016/04/201604130750449045.png$image
||static.larissanet.gr/wp-content/uploads/2018/09/201809031313488912.gif$image
||static.larissanet.gr/wp-content/uploads/2018/03/201803060707089940.jpg$image
||static.larissanet.gr/wp-content/uploads/2017/12/201712231617516964.gif$image
||static.larissanet.gr/wp-content/uploads/2015/05/201505190756575562.gif$image
||static.larissanet.gr/wp-content/uploads/2018/04/201804171349015458.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/03/201803300040407707.gif$image
||static.larissanet.gr/wp-content/uploads/2018/10/201810121049021594.jpg$image
||static.larissanet.gr/wp-content/uploads/2018/04/201804301202379195.gif$image
||static.larissanet.gr/wp-content/uploads/2018/03/201803151459175716.png$image
www.larissanet.gr##.fixed > div.inner:nth-of-type(2)
www.larissanet.gr##.sidebar > div.widget_sp_image.box_outer:nth-of-type(1)
www.larissanet.gr##.sidebar > div.widget_sp_image.box_outer:nth-of-type(2)
www.larissanet.gr##.sidebar > div.widget_sp_image.box_outer:nth-of-type(3)
www.larissanet.gr##div.row-fluid:nth-of-type(2)
www.larissanet.gr##div.row-fluid:nth-of-type(4)
www.larissanet.gr##div.row-fluid:nth-of-type(8)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(11)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(12)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(13)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(14)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(15)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(16)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(17)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(18)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(19)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(20)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(21)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(22)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(23)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(24)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(25)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(26)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(27)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(28)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(30)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(31)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(32)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(33)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(34)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(35)
www.larissanet.gr##div.widget_sp_image.box_outer:nth-of-type(36)
www.larissanet.gr##div.enhanced-text-widget.widget_text.box_outer.banner:nth-of-type(37)
www.larissanet.gr##div.row-fluid:nth-of-type(10)
www.larissanet.gr##div.row-fluid:nth-of-type(14) > .widget-area > div.widget_sp_image.box_outer:nth-of-type(1)
www.larissanet.gr##div.row-fluid:nth-of-type(14) > .widget-area > div.widget_sp_image.box_outer:nth-of-type(2)
www.larissanet.gr##div.row-fluid:nth-of-type(16)
www.larissanet.gr##div.row-fluid:nth-of-type(18)

||www.usay.gr/hyperads/hyperad_iframe.php$subdocument
www.usay.gr##.new60sbanners
www.usay.gr##div.adds_sec:nth-of-type(4)
www.usay.gr##div.adds_sec:nth-of-type(5)

www.trolleatzis.com##[src*="postimg.cc"]

vrilissianews.gr##div.home-12.sb-widget:nth-of-type(3)
vrilissianews.gr##div.home-12.sb-widget:nth-of-type(4)
vrilissianews.gr##div.home-12.sb-widget:nth-of-type(5)
vrilissianews.gr##div.home-12.sb-widget:nth-of-type(6)

||tovatraxi.com/wp-content/uploads/2016/05/newsletterlogo.png$image
tovatraxi.com###boxzilla-9270

||www.realestatenews.gr/images/stories/250px.gif$image
||www.realestatenews.gr/images/stories/para_250x300.gif$image
||www.realestatenews.gr/images/stories/logo-sygkatoikos-ren-a.gif$image
||www.realestatenews.gr/images/stories/pomidaani.gif$image
||www.realestatenews.gr/images/stories/nomisma_140x60.gif$image
||www.realestatenews.gr/images/stories/baner-pontiki.gif$image
||www.realestatenews.gr/images/stories/1theloakinita5.gif$image
||www.realestatenews.gr/images/stories/logo-sygkatoikos-ren-a.gif$image
||www.realestatenews.gr/images/stories/250px.gif$image
||www.realestatenews.gr/images/stories/pomidaani.gif$image
||www.realestatenews.gr/images/stories/nomisma_140x60.gif$image
||www.realestatenews.gr/images/stories/baner-pontiki.gif$image
||www.realestatenews.gr/images/stories/banner-red.swf$object
||www.realestatenews.gr/images/stories/para_250x300.gif$image`

**Comment by kargig** [comment]
feel free to create more MRs for the above rules

**Comment by patrickdrd** [comment]
what's "MR"?

**Comment by kargig** [comment]
ooops sorry, MR (merge request) is gitlab terminology.
PR (pull request) is what github uses :)

**Comment by patrickdrd** [comment]
me? I'm not sure I can, I'm just a simple user
