### ISSUE TITLE
eleftheria.gr

### ISSUE THREAD

**Issue by patrickdrd** [kargig/greek-adblockplus-filter#37]
e.g.
https://www.eleftheria.gr/%CE%BF%CE%B9%CE%BA%CE%BF%CE%BD%CE%BF%CE%BC%CE%AF%CE%B1/item/217190-%CE%BE%CE%B5%CF%87%CF%89%CF%81%CE%B9%CF%83%CF%84%CE%AD%CF%82-%CF%86%CE%BF%CF%81%CE%BF%CE%BB%CE%BF%CE%B3%CE%B9%CE%BA%CE%AD%CF%82-%CE%B4%CE%B7%CE%BB%CF%8E%CF%83%CE%B5%CE%B9%CF%82-%CE%B1%CF%80%CF%8C-%CF%84%CE%B1-%CE%B6%CE%B5%CF%85%CE%B3%CE%AC%CF%81%CE%B9%CE%B1.html

**Comment by patrickdrd** [comment]
yeah, I know, but I thought this was your job,
anyway, here are them:

||eleftheria.gr/IMAGES/BANNERS^
eleftheria.gr##[src*="/BANNERS/"]
eleftheria.gr##[src*="/banners/"]
eleftheria.gr##div.title.sp-module:nth-of-type(5)

as for the others (the list I posted), if you want you can include them,
I've got them in my list anyway

**Comment by kargig** [comment]
This is no "job" for me. This is done on my free time...
Everyone is free to suggest changes if they want. If the changes are in the proper format and can be directly added to the repo/list then there are greater chances this happens quicker than when I have to find the URLs myself.
