### ISSUE TITLE
usay.gr

### ISSUE THREAD

**Issue by patrickdrd** [kargig/greek-adblockplus-filter#39]
I've got these too:

```
||usay.gr/hyperads/hyperad_iframe.php$subdocument
usay.gr##.new60sbanners
```

**Comment by kargig** [comment]
should be fixed by https://github.com/kargig/greek-adblockplus-filter/commit/f43d9db8f2981d191605e2b9f96c9fcbc409813d

**Comment by kargig** [comment]
commit https://github.com/kargig/greek-adblockplus-filter/commit/87f7724f7f37798b61797a88c0ff9cf1f6a22b33 should be able to handle all these
