### ISSUE TITLE
imerodromos.gr

### ISSUE THREAD

**Issue by patrickdrd** [kargig/greek-adblockplus-filter#41]
```
||imerodromos.gr/wp-content/uploads/2018/05/Tiniakosgr.gif$image
||imerodromos.gr/wp-content/uploads/2018/11/500X417_COLUMBIA.jpg$image
||imerodromos.gr/wp-content/uploads/2018/11/500X417_MARCOS.jpg$image
||imerodromos.gr/wp-content/uploads/2018/11/500X417_MARX.jpg$image
||imerodromos.gr/wp-content/uploads/2018/07/BoukoviBanner-500x417.jpg$image
||imerodromos.gr/wp-content/uploads/2018/12/MEGALH-ISTORIA-THS-ELLADAS-2.jpg$image
||imerodromos.gr/wp-content/uploads/2018/12/MEGALH-ISTORIA-THS-ELLADAS-1.jpg$image
||imerodromos.gr/wp-content/uploads/2017/06/collectives1-20.jpg$image
imerodromos.gr##.elementor-top-section.elementor-section.elementor-section-height-default.elementor-section-boxed.elementor-element-4162913.elementor-element.has_ae_slider > .elementor-column-gap-default.elementor-container > .elementor-row
||imerodromos.gr/wp-content/uploads/2018/07/kraounakis1.jpg$image
||imerodromos.gr/wp-content/uploads/2018/12/na_ntysoume_tous_gymnous_500x417pix-2-1.gif$image
imerodromos.gr##.elementor-inner-column.elementor-col-33.elementor-column.elementor-element-7e87.elementor-element.has_ae_slider > .elementor-element-populated.elementor-column-wrap
||imerodromos.gr/wp-content/uploads/2017/02/podium-2.gif$image
||imerodromos.gr/wp-content/uploads/2018/05/Screen-Shot-2018-05-07-at-20.41.56.png$image
||imerodromos.gr/wp-content/uploads/2018/04/BANER_ASFALISTIKO_300X249.jpg$image
imerodromos.gr##.elementor-top-column.elementor-col-50.elementor-column.elementor-element-fc62ef0.elementor-element.has_ae_slider > .elementor-element-populated.elementor-column-wrap > .elementor-widget-wrap
```

**Comment by kargig** [comment]
closed by https://github.com/kargig/greek-adblockplus-filter/commit/91867f47f14e6eb264e69b7cbdca4a5ab4cb0409

**Comment by kargig** [comment]
> also, it needs more work:
> 
> ```
> imerodromos.gr##.elementor-widget-news247-title.elementor-widget.elementor-element > .elementor-widget-container
> ```
When this gets added then a lot of headlines on top of columns get removed. This is not supposed to happen with by adblock filter.
> ```
> imerodromos.gr##[href="http://tiniakos.gr/"]
> ```
already blocked by another rule
> ```
> ||imerodromos.gr/wp-content/uploads/2018/07/kraounakis1.jpg$image
> ```
not an ad
> ```
> ||imerodromos.gr/wp-content/uploads/2018/07/hmerodromos-enisxysh-av.jpg$image
> ```
not an ad
> ```
> ||imerodromos.gr/wp-content/uploads/2018/12/na_ntysoume_tous_gymnous_500x417pix-2-1.gif$image
> ```
already blocked
> ```
> imerodromos.gr##[src*="na_ntysoume_tous_gymnous"]
> ```
isn't the above already enough ?
> ```
> ||imerodromos.gr/wp-content/uploads/2018/04/BANER_ASFALISTIKO_300X249.jpg$image
> ```
already blocked
> ```
> www.imerodromos.gr##[src*="/BANER"]
> ```
isn't the above already enough ?
> ```
> 
> repleace your "elementor-element" filters with the first one, because this one changes every time

It's not clear to me what you mean. Please send a diff/PR with your proposed changes.

**Comment by patrickdrd** [comment]
1) about the "isn't the above already enough ?":
no, it isn't because if you refresh the page using ctrl+f5 (cache ignored),
you'll see that place-holders remain
2) about the last one, as I told you again, I'm not a github developer, so I don't understand and/or know the terminology you're talking about, anyway,
I said that in these filters:

`imerodromos.gr##.elementor-inner-column.elementor-col-33.elementor-column.elementor-element-7f24.elementor-element.has_ae_slider`

the "7f24" part changes each time (each time the page is loaded maybe?),
that's  why I switched to the first one:

`imerodromos.gr##.elementor-widget-news247-title.elementor-widget.elementor-element > .elementor-widget-container`

I hadn't notice the problems you mention though

anyway
3) I've also said that you can remove the "www." part from in front of all the urls,
the filters work fine without it, I checked

**Comment by patrickdrd** [comment]
"You must be on a branch to make or propose changes to this file"
