### ISSUE TITLE
static.adman.gr on web.ert.gr

### ISSUE THREAD

**Issue by patrickdrd** [kargig/greek-adblockplus-filter#50]
you need to unblock adman.gr from ert.gr,
check this out:
https://forum.adguard.com/index.php?threads/static-adman-gr-on-web-ert-gr.31509/

**Comment by kargig** [comment]
The video player works for me using uBlock origin on google-chrome with ert.adman.gr blocked by Easylist.

Easylist contains: `||adman.gr^$third-party`
Peter Lowe’s Ad and tracking server list contains: `127.0.0.1 adman.gr`
Greek AdBlocking filters contain:
```
adman.otenet.gr/*
furious.adman.gr
obj.adman.gr
r2d2.adman.gr/gbanner/
static.adman.gr
||adman.in.gr/gbanner/
||adman.kathimerini.gr/*
||bold.adman.gr/*
##A[href*="adman.otenet.gr/click?"]
autotriti.gr##strong > a[href^="http://autotriti.adman.gr/click"]
gr##A[href*="http://bold.adman.gr/"]
gr##A[href*="http://furious.adman.gr/"]
gr##A[href*="http://talos.adman.gr/"]
kathimerini.gr##A[href*="http://adman.kathimerini.gr/"]
@@|http://adman.in.gr/gbanner/?*|1195/300x250
@@||www.antenna.gr/js/adman-video*.js$script,domain=www.antenna.gr
```
nothing related to ert.adman.gr.

According to the above, I don't consider this a problem with the Greek AdBlocking filters.
You need to provide further details if you want me to debug this further.

**Comment by patrickdrd** [comment]
the problem is in static.adman.gr, it has to be unblocked for web.ert.gr videos to display and load properly, that's why I added it as an exception

**Comment by kargig** [comment]
As I've said in my previous comment, web.ert.gr works fine with Easylist + the Greek AdBlocking filters using uBlock origin, even with static.adman.gr blocked. Maybe the problem is with Adguard. 

Please test whether this website works with uBlock origin and/or adblockplus. If using those two also works for you, as I think they do, then the problem is adguard.

**Comment by patrickdrd** [comment]
yes, the problem is with adguard, that's why I opened an issue on their forum, waiting for them to whitelist it, anyway, ok, you can close the issue then

**Comment by kargig** [comment]
Thank you for your prompt feedback.
