### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by fumantsu** [kargig/greek-adblockplus-filter#52]
Both FF and Chrome gives an error Failed, not a valid address. Not sure the reason but If I click the "source" button the list is visible

**Comment by kargig** [comment]
which addon are you using ? 
does this https://void.gr/kargig/void-gr-filters.txt open for you from a browser ?

**Comment by fumantsu** [comment]
The link opens. I tried as well because I was thinking something about host
down etc.

Adblock plus, the classic one.

**Comment by kargig** [comment]
If the link opens for you directly, I can't see how this can be a bug of the list. It's probably something with Adblock plus. 

Do you want to report it them maybe ?
