### ISSUE TITLE
gazzetta.gr ads

### ISSUE THREAD

**Issue by XhmikosR** [kargig/greek-adblockplus-filter#54]
Hello!

It seems gazzeta.gr has changed their ads and they use `madinad` for many ads.

**Comment by kargig** [comment]
Can you share some screenshots with the ads you see ? with my filters I only see placeholders (mostly on the right column) but no real ads on them.
If you know how to create filters maybe you can create some filters yourself and send them as PR

**Comment by XhmikosR** [comment]
I definitely see the ads, and I do use your filters with uBlock origin:

![2019-12-28_14-11-37](https://user-images.githubusercontent.com/349621/71543529-9a527480-297c-11ea-978b-cc89578be898.jpg)


Not sure how to identify the offending elements/scripts otherwise I'd make a PR.

**Comment by XhmikosR** [comment]
Thank you! This should also block the ads on the right part that I was seeing apart from the popup

**Comment by XhmikosR** [comment]
Although I updated uBlock lists after purging their caches, I still see the ads and not the rules you added. Maybe it needs some time.

**Comment by kargig** [comment]
the endpoint serving the rules is updated manually. I just did that.

Can you purge caches once again and then check if the rules added in https://github.com/kargig/greek-adblockplus-filter/commit/9d2e3ed541ae341237106349a2fd9545ab352321 exist in your local rules ?

**Comment by XhmikosR** [comment]
Now it works, confirmed!

Not sure if we should add these in another list but WTF is with website owners that think this is OK.

Thank god for pihole.

**Comment by kargig** [comment]
🎉

**Comment by XhmikosR** [comment]
@kargig: not sure if I should make a new issue but it seems this now happens on mobile only. :/

I don't see the ads when I'm at home since I have blocked the whole madinad.gr domain, but while browsing the site on mobile, I get a full page ad, for example https://www.gazzetta.gr/plus

<img src="https://user-images.githubusercontent.com/349621/95566176-e3fede00-0a29-11eb-9f6b-22aaa92a4fa8.jpg" alt="Screenshot_20201009-121922_Firefox" width="350">

**Comment by kargig** [comment]
can you please create a new issue for this ?
fwiw I can't see any ads on android using brave browser.
which mobile browser are you using and which filter lists does it load ?

**Comment by XhmikosR** [comment]
Indeed, I cannot reproduce the problem either now. I think it either was
A/B testing or they removed the full-screen ads after the backlash.
