### ISSUE TITLE
pi-hole has dropped support for AdBlock type lists :(

### ISSUE THREAD

**Issue by thagorastos** [kargig/greek-adblockplus-filter#55]
Hi all!

I read that pi-hole 4.3.2 and onwards has officially dropped support for AdBlock type lists meaning that void.gr list is no longer supported, thus parsed (https://www.zdnet.com/article/pi-hole-drops-support-for-ad-blocklists-used-by-browser-based-ad-blockers/). 😔

A quick 'n' dirty fix is to use an older pi-hole gravity.sh script version which still parses the list, but a long term solution is needed.

Any suggestions?

**Comment by kargig** [comment]
As the article you linked explains, pi-hole uses DNS-level blocking which is insufficient and error prone. 

I can only suggest that you use an adblocker like uBlock Origin or equivalent for your desktop browsers, and the officially supported lists that pi-hole and its community proposes, for the rest of your devices.
