### ISSUE TITLE
Would you want to add a licence to your list/repo?

### ISSUE THREAD

**Issue by DandelionSprout** [kargig/greek-adblockplus-filter#56]
I've simply noticed that your list doesn't have an open-source licence, meaning that it's technically still using "All Rights Reserved".

If you were to want to add one, but you're confused as to which one to choose, we can divide them into two categories: Loose licences, and strict licences.

Loose licences usually say *"You can do whatever you want with my list, just don't blame me if things go wrong, and it's nicely appreciated if you credit me."* This includes MIT, BSD-3, Unlicense, CC-0, Dandelicence, WTFPL, and Public Domain, among others.

Strict licences usually say *"You can only use this list on my terms. You must only use it in open-source projects, you must credit me in a specific way, and in some cases you can't use it in paid projects."* This includes GPLv3, LGPLv3, CC BY-NC-SA, Mozilla Public License, and Apache 2.0.

**Comment by kargig** [comment]
license is mentioned inside https://github.com/kargig/greek-adblockplus-filter/blob/master/void-gr-filters.txt

I could add a separate file though...

**Comment by DandelionSprout** [comment]
Since your list is the only significant content in this repo, it seems to me that adding a file called `LICENSE.md` which contains the text from https://creativecommons.org/licenses/by-sa/3.0/legalcode, is how GitHub and some of the more self-limiting open-source nerds out there⁽¹⁾ recommend that open-source licences should be applied.

⁽¹⁾ = Especially the somewhat strange and small niche project [*uBO-Libre*](https://www.hyperbola.info/packages/community/any/iceweasel-uxp-ublock-origin-legacy/) for Pale Moon-type web browsers, who aim to remove default lists that don't have open-source licences, and they haven't been known to dig particularly deep into the repos/lists to look for the presence of such.
