### ISSUE TITLE
Outdated Void.gr filters

### ISSUE THREAD

**Issue by aldi** [kargig/greek-adblockplus-filter#58]
I've noticed that the filter in uBlock Origin is outdated (https://www.void.gr/kargig/void-gr-filters.txt). Shouldn't it be updated automatically based on the GitHub-commited updates?
<img width="512" alt="Screenshot 2020-04-09 at 4 06 49 PM" src="https://user-images.githubusercontent.com/15065804/78898317-43c8fc00-7a7c-11ea-8607-42d69f438470.png">

**Comment by kargig** [comment]
sorry, my bad. just updated it
