### ISSUE TITLE
gazzetta.gr

### ISSUE THREAD

**Issue by bug-rules** [kargig/greek-adblockplus-filter#75]
>`https://old.reddit.com/r/uBlockOrigin/comments/k1g7uf/gazzettagr_ads/`
>
> **@Murmuring9**:

`madinad.com` is responsible for ads at `gazzetta.gr`

Also `adwebone.com` and `cdnprojectagora.s3.amazonaws.com` are bad for privacy.

---

```
||cdnprojectagora.s3.amazonaws.com/gr/gazzetta.js$script,domain=gazzetta.gr
||madinad.com^$third-party
||adwebone.com^$third-party
```

**Comment by kargig** [comment]
can you PR that maybe ?
@aldi can you help ?
