### ISSUE TITLE
filoitexnisfilosofias.com

### ISSUE THREAD

**Issue by Yuki2718** [kargig/greek-adblockplus-filter#78]
URL: `https://filoitexnisfilosofias.com/`
Issue 1: an overlay preventing the page to be shown (delay or sometimes never be shown)
<details>
<summary>Screenshot 1</summary>

![filoitexnisfilosofias1](https://user-images.githubusercontent.com/58900598/102779937-66b3fa00-43d8-11eb-9ed4-1d0cdf30edf8.png)

</details>

Issue 2: ad placeholder leftover
<details>
<summary>Screenshot 2</summary>

![filoitexnisfilosofias2](https://user-images.githubusercontent.com/58900598/102779995-8519f580-43d8-11eb-8417-40c0fa41f2d6.png)

</details>

My environment: Firefox 84.0 + uBlock Origin 1.31.0 on Windows 10, with stock filter lists + Greek AdBlock Filter minus uBlock filters - Unbreak

Note: originally reported in `https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-204#post-2975966` and fixed in uBlock filters - Unbreak (https://github.com/uBlockOrigin/uAssets/commit/9db2cd391d6d237d79863be8ec2afd422d1380fa)

**Comment by kargig** [comment]
@aldi can you take care of this one as well maybe ? :)

**Comment by Yuki2718** [comment]
Thx!
