### ISSUE TITLE
serraikanea.gr

### ISSUE THREAD

**Issue by patrickdrd** [kargig/greek-adblockplus-filter#96]
lots of work to do here:

https://serraikanea.gr/koinonia/142455-serres-tora-fortigo-vytio-sfinose-stin-gefyra-fotografies.html

I'm not doing it because I'm not in anyway connected to the site or
interested in it,
if anyone wants to deal with it, he can do it

**Comment by aldi** [comment]
@patrickdrd Damn, that website is nasty! I'll give it a go!
